### ISSUE TITLE
US 01.01.01: Add a new mood event

### ISSUE THREAD

**Issue by xyqshelly** [CMPUT301F19T08/AliMama#59]
As a participant, I want to add a mood event to my mood history, each event with the current date and time, a required emotional state, optional reason, and optional social situation.

- [x] reason inText has to be less than 20 characters
- [x] emotional state should be consistent with emoticon
- [x] Code needs to be refactored into MVP 
- [x] [Bug] app crashes when not inputting date and time
- [x] [Bug] date, time and emotional states are required field, need input validation to ensure
- [ ] Javadoc
- [ ] Testing

**Comment by XuechunHou** [comment]
Java doc and UI testing for Add/Edit mood screen is done by King and Melisse
