### ISSUE TITLE
US 01.04.01: To edit a mood event

### ISSUE THREAD

**Issue by xyqshelly** [CMPUT301F19T08/AliMama#63]
As a participant, I want to edit the details of a given mood event of mine.

- [x] reason inText has to be less than 20 characters
- [x] emotional state should be consistent with emoticon
- [x] Code needs to be refactored into MVP 
- [x] [Bug] app crashes when not inputting date and time
- [x] [Bug] date, time and emotional states are required field, need input validation to ensure
- [ ] Javadoc
- [ ] Testing

**Comment by XuechunHou** [comment]
Java doc and Ui testing are done by King and Melisse
