### ISSUE TITLE
US 05.03.01: Friend's Mood History List

### ISSUE THREAD

**Issue by xyqshelly** [CMPUT301F19T08/AliMama#68]
As a participant, I want to view as a list the most recent mood events (the most recent 1 mood event) of the other participants I am granted to follow, sorted by date and time, in reverse chronological order (most recent coming first).

- [x] friends’ mood are read-only, remove delete button
- [x] [Bug] hide add mood floating action button when viewing friends' mood
- [x] code needs to be refactored into MVP
- [ ] Javadoc

- [ ] Testing

**Comment by XuechunHou** [comment]
Java doc and UI tests are done by Melisse
